pipeline {
    agent {
        node {
            label 'worker' 
        }
   }

   stages {
        stage('Docker login') {
             steps {
                withCredentials([usernamePassword(credentialsId: 'dockerHubCreds', usernameVariable: 'DOCKERHUB_USERNAME', passwordVariable: 'DOCKERHUB_TOKEN')]) {
                sh 'echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin'
                }
            }
        }
        stage('Docker build') {
            steps{
                sh 'docker build -t terraform .'
            }
        }
        // stage('Docker tag and push') {
        //     steps {
        //         sh """
        //             docker tag terraform denisvoznik/terraform-dz:${env.BRANCH_NAME}
        //             docker push denisvoznik/terraform-dz:${env.BRANCH_NAME}
        //         """
        //     }
        // }
    }
    post { 
        success {
            withCredentials([string(credentialsId: 'GitHubTokenForJenkins', variable: 'TOKEN')]) {
                sh """
                curl -L \
                    -X POST \
                    -H "Accept: application/vnd.github+json" \
                    -H "Authorization: Bearer ${TOKEN}" \
                    -H "X-GitHub-Api-Version: 2022-11-28" \
                    https://api.github.com/repos/denisvoznik/commit-statuses/statuses/${GIT_COMMIT} \
                    -d '{"state":"success", "description":"The build succeeded!","context":"continuous-integration/jenkins"}'
                """
            }
        }
        // failure {
        //     githubNotify status: "FAILURE", description: 'Failure status'
        // }
    }
}
