pipeline {
    agent {
        node {
            label 'worker' 
        }
   }

   stages {
        stage('Docker login') {
             steps {
                withCredentials([usernamePassword(credentialsId: 'dockerHubCreds', usernameVariable: 'DOCKERHUB_USERNAME', passwordVariable: 'DOCKERHUB_TOKEN')]) {
                sh 'echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin'
                }
            }
        }
        stage('Docker build') {
            steps{
                sh 'docker build -t terraform .'
            }
        }
        stage('Docker tag and push') {
            steps {
                sh """
                    docker tag denisvoznik/terraform-dz:${env.BRANCH_NAME}
                    docker push denisvoznik/terraform-dz:${env.BRANCH_NAME}
                """
            }
        }
    }
    post { 
        success {
            withCredentials([usernamePassword(credentialsId: 'GitHubTokenForJenkins', usernameVariable: 'GITHUB_USERNAME', passwordVariable: 'GITHUB_TOKEN')]) {
                sh """
                curl -L \
                    -X POST \
                    -H "Accept: application/vnd.github+json" \
                    -H "Authorization: Bearer ${GITHUB_TOKEN}" \
                    -H "X-GitHub-Api-Version: 2022-11-28" \
                    https://api.github.com/repos/${GITHUB_USERNAME}/commit-statuses/statuses/${GIT_COMMIT} \
                    -d '{"state":"success", "description":"The build succeeded!","context":"continuous-integration/jenkins"}'
                """
            }
        }
        failure {
            withCredentials([usernamePassword(credentialsId: 'GitHubTokenForJenkins', usernameVariable: 'GITHUB_USERNAME', passwordVariable: 'GITHUB_TOKEN')]) {
                sh """
                curl -L \
                    -X POST \
                    -H "Accept: application/vnd.github+json" \
                    -H "Authorization: Bearer ${GITHUB_TOKEN}" \
                    -H "X-GitHub-Api-Version: 2022-11-28" \
                    https://api.github.com/repos/${GITHUB_USERNAME}/commit-statuses/statuses/${GIT_COMMIT} \
                    -d '{"state":"failure", "description":"The build failured!","context":"continuous-integration/jenkins"}'
                """
            }
        }
    }
}
